### ISSUE TITLE
Associate a custom domain to GitHub Pages configuration

### ISSUE THREAD

**Issue by hectcastro** [azavea/rai-measurement-tool#1]
Associate the necessary DNS records to associate `rai.azavea.com` with the GitHub Pages output generated by this repository.

**Comment by coalkettler** [comment]
@hectcastro DNS changes appear to have propagated, ready for review.

**Comment by hectcastro** [comment]
Custom domain setup is looking good. 👍

**Comment by coalkettler** [comment]
Awesome, I'll notify the folks who requested the subdomain 🙌🏻

**Comment by rossbernet** [comment]
Great. Thanks!
