### ISSUE TITLE
Remove rbernet contact info and add status note

### ISSUE THREAD

**Issue by rcheetham** [azavea/rai-measurement-tool#30]
Ross's email is in the "About" panel and we've received a request to update the data for UAE. We should probably add a note that this data is based on a date (X/X/2018 or whatever) and isn't being actively updated.

**Comment by hectcastro** [comment]
![image](https://user-images.githubusercontent.com/43639/102821996-1d4ab700-43a6-11eb-84c8-fbfbdda6d1f5.png)
